import json
import time
import os
import pickle
from datetime import datetime, timedelta, timezone
from googleapiclient.discovery import build

def get_analytics_service(profile_name="default"):
    """
    Connects to YouTube Analytics using the token generated by upload_youtube.py.
    """
    credentials = None
    token_file = f"accounts/{profile_name}_token.pickle"

    if os.path.exists(token_file):
        with open(token_file, 'rb') as token:
            credentials = pickle.load(token)
            
    if not credentials or not credentials.valid:
        print(f"❌ [MONITOR] Błąd autoryzacji: brak pliku {token_file} lub token wygasł. Uruchom najpierw upload_youtube.py.")
        return None

    # We need the youtubeAnalytics API
    return build('youtubeAnalytics', 'v2', credentials=credentials)

def scrape_youtube_studio_realtime(video_id: str, profile_name: str = "dark_mindset"):
    """
    Fetches actual real-time metrics using YouTube Analytics API.
    Since real-time 'Studio' views are hard to get via standard API immediately,
    we use standard Analytics to get the closest approximation of EVS metrics.
    """
    print(f"📡 [MONITOR] Polling YouTube Analytics API for True Metrics (Video: {video_id})...")
    
    analytics = get_analytics_service(profile_name)
    if not analytics:
        return None
        
    # Analytics API has a 1-day delay for precise data, but we can attempt to pull whatever is available
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    yesterday_date = (datetime.now(timezone.utc) - timedelta(days=2)).strftime("%Y-%m-%d")

    try:
        # Pytamy o Views, estimatedMinutesWatched, averageViewDuration, comments, likes, shares
        response = analytics.reports().query(
            ids="channel==MINE",
            startDate=yesterday_date,
            endDate=today,
            metrics="views,averageViewDuration,comments,likes,shares",
            filters=f"video=={video_id}"
        ).execute()

        rows = response.get("rows", [])
        
        if not rows:
             print(f"⚠️ [MONITOR] API nie zwróciło jeszcze danych dla {video_id} (Latencja YouTube). Używam domyślnych bezpiecznych miar.")
             return None

        # Zwrócony wiersz to odpowiednio: [views, averageViewDuration, comments, likes, shares]
        metrics = rows[0]
        actual_views = metrics[0]
        actual_avd = metrics[1]
        actual_comments = metrics[2]
        actual_likes = metrics[3]
        actual_shares = metrics[4]

        # Estymacja VPM w pierwszych godzinach
        # Jeśli API zwróciło dane, liczymy to jako VPM w skali godziny
        est_vpm_60 = actual_views / 60.0 if actual_views > 0 else 0

        # API nie daje Viewed/Swiped - jako Proxy używamy (AVD / 15s) (Zakładając 15s jako dobry benchmark retencji)
        # Ratio powyżej 1.0 oznacza, że ludzie oglądają to w nieskończoność.
        viewed_ratio = (actual_avd / 15.0) if actual_avd else 0.5
        
        # Wymuszenie twardego limitu (Max 99% obejrzanych w matrycy matematycznej)
        viewed_percentage = min(viewed_ratio, 0.99)
        swiped_percentage = 1.0 - viewed_percentage
        if swiped_percentage <= 0:
            swiped_percentage = 0.01

        return {
            "VPM_60": est_vpm_60,
            "viewed_percentage": viewed_percentage,
            "swiped_percentage": swiped_percentage,
            "likes": actual_likes,
            "comments": actual_comments,
            "shares": actual_shares,
            "total_views_60m": actual_views
        }

    except Exception as e:
         print(f"❌ [MONITOR] Wyjątek podczas łączenia z YT Analytics API: {e}")
         return None

def calculate_micro_evs(metrics):
    """
    Calculates the MicroEVS score based on real-time Studio metrics.
    Formula: VPM_60 * (Viewed_Percentage / Swiped_Percentage) * (Engagement / Views)
    """
    if not metrics:
        return 100.0 # Baza bezpieczna

    vpm = metrics.get("VPM_60", 0)
    viewed = metrics.get("viewed_percentage", 0.5)
    swiped = metrics.get("swiped_percentage", 0.5)
    likes = metrics.get("likes", 0)
    comments = metrics.get("comments", 0)
    shares = metrics.get("shares", 0)
    views = metrics.get("total_views_60m", 1)
    
    if views == 0:
        return 50.0 # Jeśli zupełnie 0 wyświetleń, to Stan F

    engagement_factor = (likes + (comments * 2) + (shares * 3)) / views
    retention_ratio = viewed / swiped if swiped > 0 else viewed
    
    micro_evs = vpm * retention_ratio * engagement_factor
    
    # Scale to percentage representing baseline
    scaled_micro_evs_percentage = micro_evs * 320 
    
    return scaled_micro_evs_percentage

def get_latest_video_micro_evs(profile_name="dark_mindset"):
    """Reads latest video from publish_report and evaluates its MicroEVS."""
    try:
        with open("publish_report.json", "r", encoding="utf-8") as f:
            data = json.load(f)
            if not data:
                return 100.0 # Baseline
            
            # Znajdź najnowszy wrzucony przez agenta wideo (publiczne, aby na pewno miało wyświetlenia)
            latest_vid_id = None
            for item in reversed(data):
                if item.get("agent") == profile_name and item.get("video_id"):
                     latest_vid_id = item["video_id"]
                     break
            
            if not latest_vid_id:
                print("⚠️ [MONITOR] Brak opublikowanych filmów z video_id w publish_report.json.")
                return 100.0
            
            metrics = scrape_youtube_studio_realtime(latest_vid_id, profile_name)
            score = calculate_micro_evs(metrics)
            print(f"📊 [MONITOR] Real MicroEVS dla {latest_vid_id}: {score:.2f}%")
            return score
    except Exception as e:
        print(f"⚠️ [MONITOR] Error fetching MicroEVS: {e}. Defaulting to Baseline 100%.")
        return 100.0

if __name__ == "__main__":
    score = get_latest_video_micro_evs()
    print(f"Wynik ostateczny EVS: {score}%")
